export default function Head() {
  return (
    <>
      <title>Panaverse Dao</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create Panaverse Dao" />
      <link rel="icon" href="/logo3.png" />
    </>
  )
}
